"""
Create prompt_config table

Revision ID: 001
Revises: 
Create Date: 2026-01-16 15:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '001'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt_config',
    sa.Column('id', sa.Integer(), nullable=False, autoincrement=True),
    sa.Column('project_id', sa.String(100), nullable=False),
    sa.Column('prompt_type', sa.Enum('intent_recognition', 'table_selection', 'sql_generation', 'sql_error_recovery', 'data_interpretation', 'fluctuation_attribution', 'follow_up_handling', 'analysis_strategy_application', name='prompttype'), nullable=False),
    sa.Column('prompt_category', sa.String(100), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('user_prompt_template', sa.Text(), nullable=False),
    sa.Column('examples', sa.JSON(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True, default=0.7),
    sa.Column('max_tokens', sa.Integer(), nullable=True, default=2048),
    sa.Column('enabled', sa.Boolean(), nullable=True, default=True),
    sa.Column('created_by', sa.String(100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True, server_default=sa.text('CURRENT_TIMESTAMP')), 
    sa.Column('updated_at', sa.DateTime(), nullable=True, server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prompt_config')
    # ### end Alembic commands ###
