"""
创建数据准备相关表

Revision ID: 005_create_data_preparation_tables
Revises: 004_add_knowledge_base_table
Create Date: 2026-01-26 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '005_create_data_preparation_tables'
down_revision = '004'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_tables',
    sa.Column('id', sa.String(length=36), nullable=False, comment='数据表ID（UUID）'),
    sa.Column('source_id', sa.String(length=36), nullable=False, comment='所属数据源ID'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='表名'),
    sa.Column('schema_name', sa.String(length=100), nullable=True, comment='模式名/数据库名'),
    sa.Column('description', sa.Text(), nullable=True, comment='表描述'),
    sa.Column('row_count', sa.Integer(), nullable=True, comment='行数'),
    sa.Column('column_count', sa.Integer(), nullable=True, comment='列数'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True, comment='更新时间'),
    sa.Column('status', sa.Boolean(), nullable=True, comment='是否启用'),
    sa.Column('last_refreshed', sa.DateTime(), nullable=True, comment='最后刷新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'name', name='uq_source_name'),
    sa.Index('idx_source_id', 'source_id'),
    sa.Index('idx_name', 'name'),
    sa.Index('idx_status', 'status'),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], name='fk_data_tables_source_id'),
    comment='数据表'
    )
    
    op.create_table('data_table_columns',
    sa.Column('id', sa.String(length=36), nullable=False, comment='字段ID（UUID）'),
    sa.Column('table_id', sa.String(length=36), nullable=False, comment='所属数据表ID'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='字段名'),
    sa.Column('data_type', sa.String(length=100), nullable=True, comment='数据类型'),
    sa.Column('is_primary_key', sa.Boolean(), nullable=True, comment='是否为主键'),
    sa.Column('is_foreign_key', sa.Boolean(), nullable=True, comment='是否为外键'),
    sa.Column('is_nullable', sa.Boolean(), nullable=True, comment='是否允许为空'),
    sa.Column('description', sa.Text(), nullable=True, comment='字段描述'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.Index('idx_table_id', 'table_id'),
    sa.Index('idx_name', 'name'),
    sa.ForeignKeyConstraint(['table_id'], ['data_tables.id'], name='fk_data_table_columns_table_id'),
    comment='数据表字段'
    )
    
    # 更新数据源表，添加data_tables关系
    # 这已经在data_source_model.py中定义，不需要在这里修改
    
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_table_columns')
    op.drop_table('data_tables')
    # ### end Alembic commands ###