"""
修复数据准备模块的表结构

Revision ID: 006_fix_data_preparation_tables
Revises: 005_create_data_preparation_tables
Create Date: 2026-01-27 10:00:00.000000
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '006_fix_data_preparation_tables'
down_revision = '005_create_data_preparation_tables'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 删除旧的错误表结构
    op.drop_table('data_table_columns')
    op.drop_table('data_tables')
    
    # 创建正确的 data_tables 表
    op.create_table('data_tables',
    sa.Column('id', sa.String(length=36), nullable=False, comment='数据表ID（UUID）'),
    sa.Column('data_source_id', sa.String(length=36), nullable=False, comment='数据源ID'),
    sa.Column('table_name', sa.String(length=100), nullable=False, comment='表名'),
    sa.Column('display_name', sa.String(length=100), nullable=True, comment='显示名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='描述'),
    sa.Column('data_mode', sa.Enum('DIRECT_QUERY', 'IMPORT'), nullable=False, comment='数据模式：DIRECT_QUERY或IMPORT'),
    sa.Column('status', sa.Boolean(), nullable=True, comment='是否启用'),
    sa.Column('field_count', sa.Integer(), nullable=True, comment='字段数量'),
    sa.Column('row_count', sa.Integer(), nullable=True, comment='行数'),
    sa.Column('import_status', sa.Enum('PENDING', 'IN_PROGRESS', 'SUCCESS', 'FAILED'), nullable=True, comment='导入状态'),
    sa.Column('last_sync_time', sa.DateTime(), nullable=True, comment='最后同步时间'),
    sa.Column('last_refreshed', sa.DateTime(), nullable=True, comment='最后刷新时间'),
    sa.Column('created_by', sa.String(length=100), nullable=False, comment='创建人'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], name='fk_data_tables_data_source_id'),
    sa.Index('idx_data_source_id', 'data_source_id'),
    sa.Index('idx_table_name', 'table_name'),
    sa.Index('idx_data_mode', 'data_mode'),
    sa.Index('idx_status', 'status'),
    sa.Index('idx_import_status', 'import_status'),
    comment='数据表'
    )
    
    # 创建正确的 table_fields 表
    op.create_table('table_fields',
    sa.Column('id', sa.String(length=36), nullable=False, comment='字段ID（UUID）'),
    sa.Column('table_id', sa.String(length=36), nullable=False, comment='数据表ID'),
    sa.Column('field_name', sa.String(length=100), nullable=False, comment='字段名'),
    sa.Column('display_name', sa.String(length=100), nullable=True, comment='显示名称'),
    sa.Column('data_type', sa.String(length=50), nullable=False, comment='数据类型'),
    sa.Column('description', sa.Text(), nullable=True, comment='描述'),
    sa.Column('is_primary_key', sa.Boolean(), nullable=True, comment='是否为主键'),
    sa.Column('is_nullable', sa.Boolean(), nullable=True, comment='是否允许为空'),
    sa.Column('default_value', sa.String(length=255), nullable=True, comment='默认值'),
    sa.Column('dictionary_id', sa.String(length=36), nullable=True, comment='字典ID'),
    sa.Column('is_queryable', sa.Boolean(), nullable=True, comment='是否可查询'),
    sa.Column('is_aggregatable', sa.Boolean(), nullable=True, comment='是否可聚合'),
    sa.Column('sort_order', sa.Integer(), nullable=True, comment='排序顺序'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.ForeignKeyConstraint(['table_id'], ['data_tables.id'], name='fk_table_fields_table_id'),
    sa.ForeignKeyConstraint(['dictionary_id'], ['dictionaries.id'], name='fk_table_fields_dictionary_id'),
    sa.Index('idx_table_id', 'table_id'),
    sa.Index('idx_field_name', 'field_name'),
    sa.Index('idx_dictionary_id', 'dictionary_id'),
    sa.Index('idx_is_queryable', 'is_queryable'),
    sa.Index('idx_is_aggregatable', 'is_aggregatable'),
    sa.Index('idx_sort_order', 'sort_order'),
    comment='表字段'
    )
    
    # 创建正确的 dictionaries 表
    op.create_table('dictionaries',
    sa.Column('id', sa.String(length=36), nullable=False, comment='字典ID（UUID）'),
    sa.Column('code', sa.String(length=50), nullable=False, comment='字典编码'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='字典名称'),
    sa.Column('parent_id', sa.String(length=36), nullable=True, comment='父字典ID'),
    sa.Column('description', sa.Text(), nullable=True, comment='描述'),
    sa.Column('dict_type', sa.String(length=50), nullable=True, comment='字典类型'),
    sa.Column('status', sa.Boolean(), nullable=True, comment='是否启用'),
    sa.Column('sort_order', sa.Integer(), nullable=True, comment='排序顺序'),
    sa.Column('created_by', sa.String(length=100), nullable=False, comment='创建人'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_dictionary_code'),
    sa.ForeignKeyConstraint(['parent_id'], ['dictionaries.id'], name='fk_dictionaries_parent_id'),
    sa.Index('idx_code', 'code'),
    sa.Index('idx_parent_id', 'parent_id'),
    sa.Index('idx_status', 'status'),
    sa.Index('idx_sort_order', 'sort_order'),
    comment='字典'
    )
    
    # 创建正确的 dictionary_items 表
    op.create_table('dictionary_items',
    sa.Column('id', sa.String(length=36), nullable=False, comment='字典项ID（UUID）'),
    sa.Column('dictionary_id', sa.String(length=36), nullable=False, comment='字典ID'),
    sa.Column('item_key', sa.String(length=100), nullable=False, comment='键值'),
    sa.Column('item_value', sa.String(length=255), nullable=False, comment='值'),
    sa.Column('description', sa.Text(), nullable=True, comment='描述'),
    sa.Column('sort_order', sa.Integer(), nullable=True, comment='排序顺序'),
    sa.Column('status', sa.Boolean(), nullable=True, comment='是否启用'),
    sa.Column('extra_data', sa.JSON(), nullable=True, comment='额外数据'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.ForeignKeyConstraint(['dictionary_id'], ['dictionaries.id'], name='fk_dictionary_items_dictionary_id'),
    sa.UniqueConstraint('dictionary_id', 'item_key', name='uq_dictionary_item'),
    sa.Index('idx_dictionary_id', 'dictionary_id'),
    sa.Index('idx_item_key', 'item_key'),
    sa.Index('idx_status', 'status'),
    sa.Index('idx_sort_order', 'sort_order'),
    comment='字典项'
    )
    
    # 创建正确的 dynamic_dictionary_configs 表
    op.create_table('dynamic_dictionary_configs',
    sa.Column('id', sa.String(length=36), nullable=False, comment='动态字典配置ID（UUID）'),
    sa.Column('dictionary_id', sa.String(length=36), nullable=False, comment='字典ID'),
    sa.Column('data_source_id', sa.String(length=36), nullable=False, comment='数据源ID'),
    sa.Column('sql_query', sa.Text(), nullable=False, comment='SQL查询语句'),
    sa.Column('key_field', sa.String(length=100), nullable=False, comment='键字段名'),
    sa.Column('value_field', sa.String(length=100), nullable=False, comment='值字段名'),
    sa.Column('refresh_interval', sa.Integer(), nullable=True, comment='刷新间隔（秒）'),
    sa.Column('last_refresh_time', sa.DateTime(), nullable=True, comment='最后刷新时间'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.ForeignKeyConstraint(['dictionary_id'], ['dictionaries.id'], name='fk_dynamic_dictionary_configs_dictionary_id'),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], name='fk_dynamic_dictionary_configs_data_source_id'),
    sa.Index('idx_dictionary_id', 'dictionary_id'),
    sa.Index('idx_data_source_id', 'data_source_id'),
    sa.Index('idx_last_refresh_time', 'last_refresh_time'),
    comment='动态字典配置'
    )
    
    # 创建正确的 table_relations 表
    op.create_table('table_relations',
    sa.Column('id', sa.String(length=36), nullable=False, comment='关联ID（UUID）'),
    sa.Column('relation_name', sa.String(length=100), nullable=False, comment='关联名称'),
    sa.Column('primary_table_id', sa.String(length=36), nullable=False, comment='主表ID'),
    sa.Column('primary_field_id', sa.String(length=36), nullable=False, comment='主表字段ID'),
    sa.Column('foreign_table_id', sa.String(length=36), nullable=False, comment='外键表ID'),
    sa.Column('foreign_field_id', sa.String(length=36), nullable=False, comment='外键字段ID'),
    sa.Column('join_type', sa.Enum('INNER', 'LEFT', 'RIGHT', 'FULL'), nullable=False, comment='连接类型'),
    sa.Column('description', sa.Text(), nullable=True, comment='描述'),
    sa.Column('status', sa.Boolean(), nullable=True, comment='是否启用'),
    sa.Column('created_by', sa.String(length=100), nullable=False, comment='创建人'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.ForeignKeyConstraint(['primary_table_id'], ['data_tables.id'], name='fk_table_relations_primary_table_id'),
    sa.ForeignKeyConstraint(['primary_field_id'], ['table_fields.id'], name='fk_table_relations_primary_field_id'),
    sa.ForeignKeyConstraint(['foreign_table_id'], ['data_tables.id'], name='fk_table_relations_foreign_table_id'),
    sa.ForeignKeyConstraint(['foreign_field_id'], ['table_fields.id'], name='fk_table_relations_foreign_field_id'),
    sa.UniqueConstraint('primary_table_id', 'primary_field_id', 'foreign_table_id', 'foreign_field_id', name='uq_table_relation'),
    sa.Index('idx_relation_name', 'relation_name'),
    sa.Index('idx_primary_table_id', 'primary_table_id'),
    sa.Index('idx_primary_field_id', 'primary_field_id'),
    sa.Index('idx_foreign_table_id', 'foreign_table_id'),
    sa.Index('idx_foreign_field_id', 'foreign_field_id'),
    sa.Index('idx_join_type', 'join_type'),
    sa.Index('idx_status', 'status'),
    comment='表关联'
    )
    
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('table_relations')
    op.drop_table('dynamic_dictionary_configs')
    op.drop_table('dictionary_items')
    op.drop_table('dictionaries')
    op.drop_table('table_fields')
    op.drop_table('data_tables')
    # ### end Alembic commands ###
