"""
完善数据表数据库设计

Revision ID: 007_complete_data_table_design
Revises: 20260130182038_add_table_folders
Create Date: 2026-02-03 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '007_complete_data_table_design'
down_revision = '20260130182038_add_table_folders'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. 为 data_tables 表添加缺失的索引和约束
    # 添加复合唯一索引，确保同一数据源下表名唯一
    op.create_index('idx_data_source_table_unique', 'data_tables', ['data_source_id', 'table_name'], unique=True)
    
    # 2. 为 table_fields 表添加复合索引，提高查询性能
    # 添加复合索引：表ID + 字段名，确保同一表下字段名唯一
    op.create_index('idx_table_field_unique', 'table_fields', ['table_id', 'field_name'], unique=True)
    
    # 添加复合索引：表ID + 排序顺序，用于字段排序查询
    op.create_index('idx_table_sort_order', 'table_fields', ['table_id', 'sort_order'])
    
    # 3. 为 dictionaries 表添加性能优化索引
    # 添加复合索引：状态 + 排序顺序，用于启用字典的排序查询
    op.create_index('idx_dict_status_sort', 'dictionaries', ['status', 'sort_order'])
    
    # 4. 为 dictionary_items 表添加性能优化索引
    # 添加复合索引：字典ID + 状态 + 排序顺序，用于获取启用的字典项
    op.create_index('idx_dict_item_status_sort', 'dictionary_items', ['dictionary_id', 'status', 'sort_order'])
    
    # 5. 为 table_relations 表添加性能优化索引
    # 添加复合索引：主表ID + 状态，用于查询表的有效关联
    op.create_index('idx_primary_table_status', 'table_relations', ['primary_table_id', 'status'])
    
    # 添加复合索引：外键表ID + 状态，用于查询表的有效关联
    op.create_index('idx_foreign_table_status', 'table_relations', ['foreign_table_id', 'status'])
    
    # 6. 添加数据表同步历史记录表（用于跟踪表结构变更）
    op.create_table('data_table_sync_history',
    sa.Column('id', sa.String(length=36), nullable=False, comment='同步历史ID（UUID）'),
    sa.Column('table_id', sa.String(length=36), nullable=False, comment='数据表ID'),
    sa.Column('sync_type', sa.Enum('STRUCTURE_SYNC', 'DATA_IMPORT', 'FIELD_UPDATE'), nullable=False, comment='同步类型'),
    sa.Column('sync_status', sa.Enum('STARTED', 'IN_PROGRESS', 'SUCCESS', 'FAILED'), nullable=False, comment='同步状态'),
    sa.Column('sync_message', sa.Text(), nullable=True, comment='同步消息'),
    sa.Column('fields_added', sa.Integer(), default=0, comment='新增字段数'),
    sa.Column('fields_updated', sa.Integer(), default=0, comment='更新字段数'),
    sa.Column('fields_removed', sa.Integer(), default=0, comment='删除字段数'),
    sa.Column('rows_imported', sa.Integer(), nullable=True, comment='导入行数'),
    sa.Column('sync_duration', sa.Integer(), nullable=True, comment='同步耗时（秒）'),
    sa.Column('created_by', sa.String(length=100), nullable=False, comment='操作人'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('completed_at', sa.DateTime(), nullable=True, comment='完成时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.ForeignKeyConstraint(['table_id'], ['data_tables.id'], name='fk_sync_history_table_id', ondelete='CASCADE'),
    sa.Index('idx_sync_table_id', 'table_id'),
    sa.Index('idx_sync_type', 'sync_type'),
    sa.Index('idx_sync_status', 'sync_status'),
    sa.Index('idx_sync_created_at', 'created_at'),
    comment='数据表同步历史'
    )
    
    # 7. 添加表字段变更历史记录表（用于跟踪字段级别的变更）
    op.create_table('table_field_history',
    sa.Column('id', sa.String(length=36), nullable=False, comment='字段历史ID（UUID）'),
    sa.Column('field_id', sa.String(length=36), nullable=False, comment='字段ID'),
    sa.Column('table_id', sa.String(length=36), nullable=False, comment='数据表ID'),
    sa.Column('change_type', sa.Enum('CREATED', 'UPDATED', 'DELETED'), nullable=False, comment='变更类型'),
    sa.Column('field_name', sa.String(length=100), nullable=False, comment='字段名'),
    sa.Column('old_data_type', sa.String(length=50), nullable=True, comment='原数据类型'),
    sa.Column('new_data_type', sa.String(length=50), nullable=True, comment='新数据类型'),
    sa.Column('old_description', sa.Text(), nullable=True, comment='原描述'),
    sa.Column('new_description', sa.Text(), nullable=True, comment='新描述'),
    sa.Column('change_reason', sa.String(length=255), nullable=True, comment='变更原因'),
    sa.Column('created_by', sa.String(length=100), nullable=False, comment='操作人'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.ForeignKeyConstraint(['field_id'], ['table_fields.id'], name='fk_field_history_field_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['table_id'], ['data_tables.id'], name='fk_field_history_table_id', ondelete='CASCADE'),
    sa.Index('idx_field_history_field_id', 'field_id'),
    sa.Index('idx_field_history_table_id', 'table_id'),
    sa.Index('idx_field_history_change_type', 'change_type'),
    sa.Index('idx_field_history_created_at', 'created_at'),
    comment='表字段变更历史'
    )
    
    # 8. 为现有表添加缺失的默认值
    # 为 data_tables 表的 status 字段设置默认值
    op.alter_column('data_tables', 'status', server_default=sa.text('TRUE'))
    
    # 为 table_fields 表的布尔字段设置默认值
    op.alter_column('table_fields', 'is_primary_key', server_default=sa.text('FALSE'))
    op.alter_column('table_fields', 'is_nullable', server_default=sa.text('TRUE'))
    op.alter_column('table_fields', 'is_queryable', server_default=sa.text('TRUE'))
    op.alter_column('table_fields', 'is_aggregatable', server_default=sa.text('TRUE'))
    op.alter_column('table_fields', 'sort_order', server_default=sa.text('0'))
    
    # 为 dictionaries 表的字段设置默认值
    op.alter_column('dictionaries', 'status', server_default=sa.text('TRUE'))
    op.alter_column('dictionaries', 'sort_order', server_default=sa.text('0'))
    
    # 为 dictionary_items 表的字段设置默认值
    op.alter_column('dictionary_items', 'status', server_default=sa.text('TRUE'))
    op.alter_column('dictionary_items', 'sort_order', server_default=sa.text('0'))
    
    # 为 table_relations 表的字段设置默认值
    op.alter_column('table_relations', 'status', server_default=sa.text('TRUE'))
    
    # 为 dynamic_dictionary_configs 表的字段设置默认值
    op.alter_column('dynamic_dictionary_configs', 'refresh_interval', server_default=sa.text('3600'))
    
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 删除新增的表
    op.drop_table('table_field_history')
    op.drop_table('data_table_sync_history')
    
    # 删除新增的索引
    op.drop_index('idx_foreign_table_status', table_name='table_relations')
    op.drop_index('idx_primary_table_status', table_name='table_relations')
    op.drop_index('idx_dict_item_status_sort', table_name='dictionary_items')
    op.drop_index('idx_dict_status_sort', table_name='dictionaries')
    op.drop_index('idx_table_sort_order', table_name='table_fields')
    op.drop_index('idx_table_field_unique', table_name='table_fields')
    op.drop_index('idx_data_source_table_unique', table_name='data_tables')
    
    # 移除默认值（注意：这可能会影响现有数据）
    op.alter_column('dynamic_dictionary_configs', 'refresh_interval', server_default=None)
    op.alter_column('table_relations', 'status', server_default=None)
    op.alter_column('dictionary_items', 'sort_order', server_default=None)
    op.alter_column('dictionary_items', 'status', server_default=None)
    op.alter_column('dictionaries', 'sort_order', server_default=None)
    op.alter_column('dictionaries', 'status', server_default=None)
    op.alter_column('table_fields', 'sort_order', server_default=None)
    op.alter_column('table_fields', 'is_aggregatable', server_default=None)
    op.alter_column('table_fields', 'is_queryable', server_default=None)
    op.alter_column('table_fields', 'is_nullable', server_default=None)
    op.alter_column('table_fields', 'is_primary_key', server_default=None)
    op.alter_column('data_tables', 'status', server_default=None)
    
    # ### end Alembic commands ###