"""
数据表数据库设计完善（简化版）

Revision ID: 008_data_table_design_simplified
Revises: 20260130182038_add_table_folders
Create Date: 2026-02-03 14:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '008_data_table_design_simplified'
down_revision = '20260130182038_add_table_folders'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. 为现有表添加性能优化索引
    
    # 为 data_tables 表添加复合唯一索引，确保同一数据源下表名唯一
    try:
        op.create_index('idx_data_source_table_unique', 'data_tables', ['data_source_id', 'table_name'], unique=True)
    except Exception:
        # 索引可能已存在，忽略错误
        pass
    
    # 为 table_fields 表添加复合索引，提高查询性能
    try:
        op.create_index('idx_table_field_unique', 'table_fields', ['table_id', 'field_name'], unique=True)
    except Exception:
        pass
        
    try:
        op.create_index('idx_table_sort_order', 'table_fields', ['table_id', 'sort_order'])
    except Exception:
        pass
    
    # 为 dictionaries 表添加性能优化索引
    try:
        op.create_index('idx_dict_status_sort', 'dictionaries', ['status', 'sort_order'])
    except Exception:
        pass
    
    # 为 dictionary_items 表添加性能优化索引
    try:
        op.create_index('idx_dict_item_status_sort', 'dictionary_items', ['dictionary_id', 'status', 'sort_order'])
    except Exception:
        pass
    
    # 为 table_relations 表添加性能优化索引
    try:
        op.create_index('idx_primary_table_status', 'table_relations', ['primary_table_id', 'status'])
    except Exception:
        pass
        
    try:
        op.create_index('idx_foreign_table_status', 'table_relations', ['foreign_table_id', 'status'])
    except Exception:
        pass
    
    # 2. 为现有表添加缺失的默认值
    
    # 为 data_tables 表的 status 字段设置默认值
    try:
        op.alter_column('data_tables', 'status', server_default=sa.text('TRUE'))
    except Exception:
        pass
    
    # 为 table_fields 表的布尔字段设置默认值
    try:
        op.alter_column('table_fields', 'is_primary_key', server_default=sa.text('FALSE'))
    except Exception:
        pass
        
    try:
        op.alter_column('table_fields', 'is_nullable', server_default=sa.text('TRUE'))
    except Exception:
        pass
        
    try:
        op.alter_column('table_fields', 'is_queryable', server_default=sa.text('TRUE'))
    except Exception:
        pass
        
    try:
        op.alter_column('table_fields', 'is_aggregatable', server_default=sa.text('TRUE'))
    except Exception:
        pass
        
    try:
        op.alter_column('table_fields', 'sort_order', server_default=sa.text('0'))
    except Exception:
        pass
    
    # 为 dictionaries 表的字段设置默认值
    try:
        op.alter_column('dictionaries', 'status', server_default=sa.text('TRUE'))
    except Exception:
        pass
        
    try:
        op.alter_column('dictionaries', 'sort_order', server_default=sa.text('0'))
    except Exception:
        pass
    
    # 为 dictionary_items 表的字段设置默认值
    try:
        op.alter_column('dictionary_items', 'status', server_default=sa.text('TRUE'))
    except Exception:
        pass
        
    try:
        op.alter_column('dictionary_items', 'sort_order', server_default=sa.text('0'))
    except Exception:
        pass
    
    # 为 table_relations 表的字段设置默认值
    try:
        op.alter_column('table_relations', 'status', server_default=sa.text('TRUE'))
    except Exception:
        pass
    
    # 为 dynamic_dictionary_configs 表的字段设置默认值
    try:
        op.alter_column('dynamic_dictionary_configs', 'refresh_interval', server_default=sa.text('3600'))
    except Exception:
        pass
    
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 删除新增的索引
    try:
        op.drop_index('idx_foreign_table_status', table_name='table_relations')
    except Exception:
        pass
        
    try:
        op.drop_index('idx_primary_table_status', table_name='table_relations')
    except Exception:
        pass
        
    try:
        op.drop_index('idx_dict_item_status_sort', table_name='dictionary_items')
    except Exception:
        pass
        
    try:
        op.drop_index('idx_dict_status_sort', table_name='dictionaries')
    except Exception:
        pass
        
    try:
        op.drop_index('idx_table_sort_order', table_name='table_fields')
    except Exception:
        pass
        
    try:
        op.drop_index('idx_table_field_unique', table_name='table_fields')
    except Exception:
        pass
        
    try:
        op.drop_index('idx_data_source_table_unique', table_name='data_tables')
    except Exception:
        pass
    
    # 移除默认值（注意：这可能会影响现有数据）
    try:
        op.alter_column('dynamic_dictionary_configs', 'refresh_interval', server_default=None)
    except Exception:
        pass
        
    try:
        op.alter_column('table_relations', 'status', server_default=None)
    except Exception:
        pass
        
    try:
        op.alter_column('dictionary_items', 'sort_order', server_default=None)
    except Exception:
        pass
        
    try:
        op.alter_column('dictionary_items', 'status', server_default=None)
    except Exception:
        pass
        
    try:
        op.alter_column('dictionaries', 'sort_order', server_default=None)
    except Exception:
        pass
        
    try:
        op.alter_column('dictionaries', 'status', server_default=None)
    except Exception:
        pass
        
    try:
        op.alter_column('table_fields', 'sort_order', server_default=None)
    except Exception:
        pass
        
    try:
        op.alter_column('table_fields', 'is_aggregatable', server_default=None)
    except Exception:
        pass
        
    try:
        op.alter_column('table_fields', 'is_queryable', server_default=None)
    except Exception:
        pass
        
    try:
        op.alter_column('table_fields', 'is_nullable', server_default=None)
    except Exception:
        pass
        
    try:
        op.alter_column('table_fields', 'is_primary_key', server_default=None)
    except Exception:
        pass
        
    try:
        op.alter_column('data_tables', 'status', server_default=None)
    except Exception:
        pass
    
    # ### end Alembic commands ###