"""
添加文件夹管理功能

Revision ID: 20260130182038_add_table_folders
Revises: 006_fix_data_preparation_tables
Create Date: 2026-01-30 18:20:38.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '20260130182038_add_table_folders'
down_revision = '006_fix_data_preparation_tables'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 创建 table_folders 表
    op.create_table('table_folders',
    sa.Column('id', sa.String(length=36), nullable=False, comment='文件夹ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='文件夹名称'),
    sa.Column('parent_id', sa.String(length=36), nullable=True, comment='父文件夹ID，支持层级结构'),
    sa.Column('description', sa.Text(), nullable=True, comment='文件夹描述'),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=True, comment='排序顺序'),
    sa.Column('status', sa.Boolean(), server_default=sa.text('TRUE'), nullable=True, comment='是否启用'),
    sa.Column('created_by', sa.String(length=100), nullable=True, comment='创建人'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.ForeignKeyConstraint(['parent_id'], ['table_folders.id'], name='fk_table_folders_parent_id'),
    sa.Index('idx_name', 'name'),
    sa.Index('idx_parent_id', 'parent_id'),
    sa.Index('idx_status', 'status'),
    sa.Index('idx_sort_order', 'sort_order'),
    comment='数据表文件夹'
    )
    
    # 修改 data_tables 表，添加 folder_id 字段
    op.add_column('data_tables', sa.Column('folder_id', sa.String(length=36), nullable=True, comment='关联文件夹ID'))
    op.create_foreign_key('fk_data_tables_folder_id', 'data_tables', 'table_folders', ['folder_id'], ['id'])
    op.create_index('idx_folder_id', 'data_tables', ['folder_id'])
    
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 删除 data_tables 表中的 folder_id 字段
    op.drop_constraint('fk_data_tables_folder_id', 'data_tables', type_='foreignkey')
    op.drop_index('idx_folder_id', table_name='data_tables')
    op.drop_column('data_tables', 'folder_id')
    
    # 删除 table_folders 表
    op.drop_table('table_folders')
    # ### end Alembic commands ###
