"""Create session_context, conversation_messages, and token_usage_stats tables

Revision ID: e02a290b0975
Revises: 001
Create Date: 2026-01-16 15:22:22.379572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e02a290b0975'
down_revision: Union[str, Sequence[str], None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _mysql_table_exists(connection, name: str) -> bool:
    """空库或未执行过旧版 init.sql 时，legacy 表不存在，不可直接 DROP。"""
    r = connection.execute(
        sa.text(
            "SELECT 1 FROM information_schema.tables "
            "WHERE table_schema = DATABASE() AND table_name = :n LIMIT 1"
        ),
        {"n": name},
    )
    return r.scalar() is not None


def _drop_legacy_if_exists(connection) -> None:
    """
    删除由早期 database/init.sql 等创建的表（若存在）。
    必须先删子表再删 users / data_sources，与存在外键时一致。
    """
    def _safe_drop_indexes_then_table(table: str, *index_names: str) -> None:
        if not _mysql_table_exists(connection, table):
            return
        for iname in index_names:
            try:
                op.drop_index(iname, table_name=table)
            except Exception:
                pass
        op.drop_table(table)

    _safe_drop_indexes_then_table(
        "query_sessions",
        op.f("idx_query_sessions_session_id"),
        op.f("idx_query_sessions_user_id"),
    )
    _safe_drop_indexes_then_table(
        "query_history",
        op.f("idx_query_history_created_at"),
        op.f("idx_query_history_user_id"),
    )
    _safe_drop_indexes_then_table(
        "data_dictionary",
        op.f("idx_data_dictionary_source_id"),
    )
    _safe_drop_indexes_then_table(
        "dictionary_table",
        op.f("unique_entry"),
        op.f("idx_dictionary_table_unique"),
    )
    if _mysql_table_exists(connection, "data_sources"):
        op.drop_table("data_sources")

    if _mysql_table_exists(connection, "users"):
        try:
            op.drop_index(op.f("email"), table_name="users")
        except Exception:
            pass
        try:
            op.drop_index(op.f("username"), table_name="users")
        except Exception:
            pass
        op.drop_table("users")


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()

    # 迁移若曾执行到一半失败，表可能已创建但 alembic_version 未更新；需幂等避免重复 CREATE
    if not _mysql_table_exists(connection, "conversation_messages"):
        op.create_table(
            "conversation_messages",
            sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
            sa.Column("session_id", sa.String(length=100), nullable=False),
            sa.Column("turn", sa.Integer(), nullable=False),
            sa.Column("role", sa.Enum("user", "assistant", "system", name="role"), nullable=False),
            sa.Column("content", sa.Text(), nullable=False),
            sa.Column("parent_message_id", sa.Integer(), nullable=True),
            sa.Column("token_count", sa.Integer(), nullable=True),
            sa.Column("model_used", sa.Enum("aliyun", "local", "none", name="modelused"), nullable=True),
            sa.Column("intent", sa.String(length=100), nullable=True),
            sa.Column("query_id", sa.String(length=100), nullable=True),
            sa.Column("analysis_id", sa.String(length=100), nullable=True),
            sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
            sa.ForeignKeyConstraint(["parent_message_id"], ["conversation_messages.id"], ondelete="CASCADE"),
            sa.PrimaryKeyConstraint("id"),
        )
    for _name, _cols in (
        ("idx_parent", ["parent_message_id"]),
        ("idx_session_turn", ["session_id", "turn"]),
    ):
        try:
            op.create_index(_name, "conversation_messages", _cols, unique=False)
        except Exception:
            pass

    if not _mysql_table_exists(connection, "session_context"):
        op.create_table(
            "session_context",
            sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
            sa.Column("session_id", sa.String(length=100), nullable=False),
            sa.Column("context_type", sa.Enum("local_model", "aliyun_model", name="contexttype"), nullable=False),
            sa.Column("messages", sa.JSON(), nullable=True),
            sa.Column("token_count", sa.Integer(), nullable=True),
            sa.Column("summary", sa.Text(), nullable=True),
            sa.Column("last_summary_at", sa.DateTime(), nullable=True),
            sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
            sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
            sa.PrimaryKeyConstraint("id"),
        )

    if not _mysql_table_exists(connection, "token_usage_stats"):
        op.create_table(
            "token_usage_stats",
            sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
            sa.Column("session_id", sa.String(length=100), nullable=False),
            sa.Column("model_type", sa.Enum("local", "aliyun", name="modeltype"), nullable=False),
            sa.Column("turn", sa.Integer(), nullable=False),
            sa.Column("input_tokens", sa.Integer(), nullable=False),
            sa.Column("output_tokens", sa.Integer(), nullable=False),
            sa.Column("total_tokens", sa.Integer(), nullable=False),
            sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
            sa.PrimaryKeyConstraint("id"),
        )

    _drop_legacy_if_exists(connection)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('query_sessions',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('session_id', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('conversation', mysql.JSON(), nullable=True),
    sa.Column('last_active', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('query_sessions_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('idx_query_sessions_user_id'), 'query_sessions', ['user_id'], unique=False)
    op.create_index(op.f('idx_query_sessions_session_id'), 'query_sessions', ['session_id'], unique=False)
    op.create_table('query_history',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('query_text', mysql.TEXT(), nullable=False),
    sa.Column('generated_sql', mysql.TEXT(), nullable=True),
    sa.Column('chart_type', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('result_data', mysql.JSON(), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('query_history_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('idx_query_history_user_id'), 'query_history', ['user_id'], unique=False)
    op.create_index(op.f('idx_query_history_created_at'), 'query_history', ['created_at'], unique=False)
    op.create_table('data_dictionary',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('source_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('column_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('alias_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('data_type', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('unit', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('category', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], name=op.f('data_dictionary_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('idx_data_dictionary_source_id'), 'data_dictionary', ['source_id'], unique=False)
    op.create_table('data_sources',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('type', mysql.ENUM('mysql', 'excel', 'api'), nullable=False),
    sa.Column('connection_string', mysql.TEXT(), nullable=True),
    sa.Column('file_path', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('dictionary_table',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('table_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('field_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('value', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('label', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.Column('sort_order', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('unique_entry'), 'dictionary_table', ['table_name', 'field_name', 'value'], unique=True)
    op.create_index(op.f('idx_dictionary_table_unique'), 'dictionary_table', ['table_name', 'field_name', 'value'], unique=False)
    op.create_table('users',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('username'), 'users', ['username'], unique=True)
    op.create_index(op.f('email'), 'users', ['email'], unique=True)
    op.drop_table('token_usage_stats')
    op.drop_table('session_context')
    op.drop_index('idx_session_turn', table_name='conversation_messages')
    op.drop_index('idx_parent', table_name='conversation_messages')
    op.drop_table('conversation_messages')
    # ### end Alembic commands ###
