"""完成数据表数据库设计优化

Revision ID: fc87d1a1a7a7
Revises: 9161e8a27f98
Create Date: 2026-02-03 15:31:25.659723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc87d1a1a7a7'
down_revision: Union[str, Sequence[str], None] = '9161e8a27f98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. 创建数据表同步历史记录表（不使用外键约束）
    op.create_table('data_table_sync_history',
        sa.Column('id', sa.String(36), primary_key=True, comment='同步历史ID（UUID）'),
        sa.Column('table_id', sa.String(36), nullable=False, comment='数据表ID'),
        sa.Column('sync_type', sa.Enum('STRUCTURE_SYNC', 'DATA_IMPORT', 'FIELD_UPDATE'), nullable=False, comment='同步类型'),
        sa.Column('sync_status', sa.Enum('STARTED', 'IN_PROGRESS', 'SUCCESS', 'FAILED'), nullable=False, comment='同步状态'),
        sa.Column('sync_message', sa.Text(), nullable=True, comment='同步消息'),
        sa.Column('fields_added', sa.Integer(), default=0, comment='新增字段数'),
        sa.Column('fields_updated', sa.Integer(), default=0, comment='更新字段数'),
        sa.Column('fields_removed', sa.Integer(), default=0, comment='删除字段数'),
        sa.Column('rows_imported', sa.Integer(), nullable=True, comment='导入行数'),
        sa.Column('sync_duration', sa.Integer(), nullable=True, comment='同步耗时（秒）'),
        sa.Column('created_by', sa.String(100), nullable=False, comment='操作人'),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), comment='创建时间'),
        sa.Column('completed_at', sa.DateTime(), nullable=True, comment='完成时间'),
        comment='数据表同步历史记录'
    )
    
    # 为同步历史表创建索引
    op.create_index('idx_sync_history_table_id', 'data_table_sync_history', ['table_id'])
    op.create_index('idx_sync_history_status', 'data_table_sync_history', ['sync_status'])
    op.create_index('idx_sync_history_created_at', 'data_table_sync_history', ['created_at'])
    
    # 2. 创建表字段变更历史记录表（不使用外键约束）
    op.create_table('table_field_history',
        sa.Column('id', sa.String(36), primary_key=True, comment='字段历史ID（UUID）'),
        sa.Column('field_id', sa.String(36), nullable=False, comment='字段ID'),
        sa.Column('table_id', sa.String(36), nullable=False, comment='数据表ID'),
        sa.Column('change_type', sa.Enum('CREATED', 'UPDATED', 'DELETED'), nullable=False, comment='变更类型'),
        sa.Column('field_name', sa.String(100), nullable=False, comment='字段名'),
        sa.Column('old_data_type', sa.String(50), nullable=True, comment='原数据类型'),
        sa.Column('new_data_type', sa.String(50), nullable=True, comment='新数据类型'),
        sa.Column('old_description', sa.Text(), nullable=True, comment='原描述'),
        sa.Column('new_description', sa.Text(), nullable=True, comment='新描述'),
        sa.Column('change_reason', sa.String(255), nullable=True, comment='变更原因'),
        sa.Column('created_by', sa.String(100), nullable=False, comment='操作人'),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), comment='创建时间'),
        comment='表字段变更历史记录'
    )
    
    # 为字段历史表创建索引
    op.create_index('idx_field_history_field_id', 'table_field_history', ['field_id'])
    op.create_index('idx_field_history_table_id', 'table_field_history', ['table_id'])
    op.create_index('idx_field_history_change_type', 'table_field_history', ['change_type'])
    
    # 3. 为现有表添加缺失的默认值（安全地处理已存在的情况）
    try:
        # 为 data_tables 表的 status 字段设置默认值
        op.alter_column('data_tables', 'status', server_default=sa.text('TRUE'))
    except Exception:
        # 如果已经有默认值，忽略错误
        pass
    
    try:
        # 为 table_fields 表的布尔字段设置默认值
        op.alter_column('table_fields', 'is_primary_key', server_default=sa.text('FALSE'))
        op.alter_column('table_fields', 'is_nullable', server_default=sa.text('TRUE'))
        op.alter_column('table_fields', 'is_queryable', server_default=sa.text('TRUE'))
        op.alter_column('table_fields', 'is_aggregatable', server_default=sa.text('TRUE'))
        op.alter_column('table_fields', 'sort_order', server_default=sa.text('0'))
    except Exception:
        pass
    
    try:
        # 为 dictionaries 表的字段设置默认值
        op.alter_column('dictionaries', 'status', server_default=sa.text('TRUE'))
        op.alter_column('dictionaries', 'sort_order', server_default=sa.text('0'))
    except Exception:
        pass
    
    try:
        # 为 dictionary_items 表的字段设置默认值
        op.alter_column('dictionary_items', 'status', server_default=sa.text('TRUE'))
        op.alter_column('dictionary_items', 'sort_order', server_default=sa.text('0'))
    except Exception:
        pass
    
    try:
        # 为 table_relations 表的字段设置默认值
        op.alter_column('table_relations', 'status', server_default=sa.text('TRUE'))
    except Exception:
        pass
    
    # 4. 为现有表添加性能优化索引（安全地处理已存在的情况）
    
    # 为 table_fields 表添加复合索引，提高查询性能
    try:
        op.create_index('idx_table_field_queryable', 'table_fields', ['table_id', 'is_queryable'])
    except Exception:
        pass
        
    try:
        op.create_index('idx_table_field_aggregatable', 'table_fields', ['table_id', 'is_aggregatable'])
    except Exception:
        pass
    
    # 为 dictionaries 表添加性能优化索引
    try:
        op.create_index('idx_dict_parent_status', 'dictionaries', ['parent_id', 'status'])
    except Exception:
        pass
    
    # 为 dictionary_items 表添加性能优化索引
    try:
        op.create_index('idx_dict_item_key_status', 'dictionary_items', ['dictionary_id', 'item_key', 'status'])
    except Exception:
        pass
    
    # 为 table_relations 表添加性能优化索引
    try:
        op.create_index('idx_relation_tables', 'table_relations', ['primary_table_id', 'foreign_table_id'])
    except Exception:
        pass
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 删除新增的索引
    try:
        op.drop_index('idx_relation_tables', table_name='table_relations')
    except Exception:
        pass
        
    try:
        op.drop_index('idx_dict_item_key_status', table_name='dictionary_items')
    except Exception:
        pass
        
    try:
        op.drop_index('idx_dict_parent_status', table_name='dictionaries')
    except Exception:
        pass
        
    try:
        op.drop_index('idx_table_field_aggregatable', table_name='table_fields')
    except Exception:
        pass
        
    try:
        op.drop_index('idx_table_field_queryable', table_name='table_fields')
    except Exception:
        pass
    
    # 删除字段历史表的索引
    try:
        op.drop_index('idx_field_history_change_type', table_name='table_field_history')
        op.drop_index('idx_field_history_table_id', table_name='table_field_history')
        op.drop_index('idx_field_history_field_id', table_name='table_field_history')
    except Exception:
        pass
    
    # 删除同步历史表的索引
    try:
        op.drop_index('idx_sync_history_created_at', table_name='data_table_sync_history')
        op.drop_index('idx_sync_history_status', table_name='data_table_sync_history')
        op.drop_index('idx_sync_history_table_id', table_name='data_table_sync_history')
    except Exception:
        pass
    
    # 删除新增的表
    op.drop_table('table_field_history')
    op.drop_table('data_table_sync_history')
    
    # 移除默认值（注意：这可能会影响现有数据）
    try:
        op.alter_column('table_relations', 'status', server_default=None)
        op.alter_column('dictionary_items', 'sort_order', server_default=None)
        op.alter_column('dictionary_items', 'status', server_default=None)
        op.alter_column('dictionaries', 'sort_order', server_default=None)
        op.alter_column('dictionaries', 'status', server_default=None)
        op.alter_column('table_fields', 'sort_order', server_default=None)
        op.alter_column('table_fields', 'is_aggregatable', server_default=None)
        op.alter_column('table_fields', 'is_queryable', server_default=None)
        op.alter_column('table_fields', 'is_nullable', server_default=None)
        op.alter_column('table_fields', 'is_primary_key', server_default=None)
        op.alter_column('data_tables', 'status', server_default=None)
    except Exception:
        pass
    
    # ### end Alembic commands ###
